In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv(r"D:\COMMAT_classification sc\code\DATASET_ weka_679.csv")

In [3]:
df.head()

SSA(m2/g)  Pore size(nm)  Pore Volume (cm3/g)  Potential  Nitrogen %  \
0      630.0           1.50                  0.0       0.25         0.0   
1     1000.0           1.75                  0.0       0.25         0.0   
2     1500.0           2.50                  0.0       0.25         0.0   
3     1400.0           2.90                  0.0       0.25         0.0   
4      850.0           1.25                  0.0       0.25         0.0   

   Id/Ig  Specific Capacitance  
0    0.0                  80.0  
1    0.0                 125.0  
2    0.0                 175.0  
3    0.0                 160.0  
4    0.0                  95.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558 entries, 0 to 557
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   SSA(m2/g)             558 non-null    float64
 1   Pore size(nm)         558 non-null    float64
 2   Pore Volume (cm3/g)   558 non-null    float64
 3   Potential             558 non-null    float64
 4   Nitrogen %            558 non-null    float64
 5   Id/Ig                 558 non-null    float64
 6   Specific Capacitance  558 non-null    float64
dtypes: float64(7)
memory usage: 30.6 KB


In [5]:
df['SSA(m2/g)'] = df['SSA(m2/g)']/1000

In [6]:
df.head()

SSA(m2/g)  Pore size(nm)  Pore Volume (cm3/g)  Potential  Nitrogen %  \
0       0.63           1.50                  0.0       0.25         0.0   
1       1.00           1.75                  0.0       0.25         0.0   
2       1.50           2.50                  0.0       0.25         0.0   
3       1.40           2.90                  0.0       0.25         0.0   
4       0.85           1.25                  0.0       0.25         0.0   

   Id/Ig  Specific Capacitance  
0    0.0                  80.0  
1    0.0                 125.0  
2    0.0                 175.0  
3    0.0                 160.0  
4    0.0                  95.0

In [7]:
df = df.rename(columns={'SSA(m2/g)': 'SSA','Pore size(nm)': 'PS', 'Pore Volume (cm3/g)': 'PV' , 'Nitrogen %':'NC' ,  'Specific Capacitance':'SC'})

In [8]:
df.head()

SSA    PS   PV  Potential   NC  Id/Ig     SC
0  0.63  1.50  0.0       0.25  0.0    0.0   80.0
1  1.00  1.75  0.0       0.25  0.0    0.0  125.0
2  1.50  2.50  0.0       0.25  0.0    0.0  175.0
3  1.40  2.90  0.0       0.25  0.0    0.0  160.0
4  0.85  1.25  0.0       0.25  0.0    0.0   95.0

In [9]:
# check unique values in dataset
df.apply(lambda x: len(x.unique()))

SSA          441
PS           177
PV           223
Potential     21
NC           129
Id/Ig        113
SC           330
dtype: int64

In [10]:
df.describe()

SSA          PS          PV   Potential          NC       Id/Ig  \
count  558.000000  558.000000  558.000000  558.000000  558.000000  558.000000   
mean     1.166802    1.714821    0.867994    1.296057    1.329385    0.555733   
std      0.883202    2.616503    0.861877    0.792527    2.875535    0.798127   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.461500    0.000000    0.238000    1.000000    0.000000    0.000000   
50%      1.016700    0.900000    0.690000    1.000000    0.000000    0.000000   
75%      1.641000    2.522500    1.295000    1.000000    1.137500    0.997500   
max      4.073000   27.200000    5.910000    4.000000   19.800000    4.540000   

               SC  
count  558.000000  
mean   188.130824  
std    104.478231  
min      0.000000  
25%    120.000000  
50%    176.500000  
75%    247.750000  
max    587.000000

In [11]:
def assign_class(value):
    if value <= 138:
        return 1
    elif value <= 223:
        return 2
    else:
        return 3

df['Output_Class'] = df['SC'].apply(assign_class)
# Check the distribution of output classes
print("\nClass Distribution:")
print(df['Output_Class'].value_counts())


Class Distribution:
Output_Class
1    187
2    186
3    185
Name: count, dtype: int64


In [12]:
# split the data as df1,df2 and df3
df1 = df[df['Output_Class'] == 1]
df2 = df[df['Output_Class'] == 2]
df3 = df[df['Output_Class'] == 3]

In [13]:
#drop specific capacitance column for classification
# Drop column ''
dfop = df.drop(columns=['SC'])
#dfop = df.drop(columns=[df.columns[6]], inplace=True)
dfop.head()

SSA    PS   PV  Potential   NC  Id/Ig  Output_Class
0  0.63  1.50  0.0       0.25  0.0    0.0             1
1  1.00  1.75  0.0       0.25  0.0    0.0             1
2  1.50  2.50  0.0       0.25  0.0    0.0             2
3  1.40  2.90  0.0       0.25  0.0    0.0             2
4  0.85  1.25  0.0       0.25  0.0    0.0             1

In [14]:
# Check Unique Values for each variable.
for i in dfop.columns:
  print(f"Unique {i}'s count:{dfop[i].nunique()}\n------------------------------------------")
  if i in dfop.columns:
    if(dfop[i].nunique() < 12):
      print(f"\n{dfop[i].unique()}\n------------------------------------------")
     

Unique SSA's count:441
------------------------------------------
Unique PS's count:177
------------------------------------------
Unique PV's count:223
------------------------------------------
Unique Potential's count:21
------------------------------------------
Unique NC's count:129
------------------------------------------
Unique Id/Ig's count:113
------------------------------------------
Unique Output_Class's count:3
------------------------------------------

[1 2 3]
------------------------------------------


In [15]:
import os
print(os.getcwd())  # Shows the current working directory

C:\Users\HP\Desktop\Document\COMMAT\code


In [16]:
from sklearn.model_selection import train_test_split, learning_curve
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc, precision_recall_curve, accuracy_score 

In [17]:
# To select all columns except the last one for X1, and the last column for y1 for  regression analysis of classes:
Xop = dfop.iloc[:, :-1]  # Select all columns except the last one for features (X1)
yop = dfop.iloc[:, -1]   # Select the last column as the target (y1)

In [18]:
Xop.head()

SSA    PS   PV  Potential   NC  Id/Ig
0  0.63  1.50  0.0       0.25  0.0    0.0
1  1.00  1.75  0.0       0.25  0.0    0.0
2  1.50  2.50  0.0       0.25  0.0    0.0
3  1.40  2.90  0.0       0.25  0.0    0.0
4  0.85  1.25  0.0       0.25  0.0    0.0

In [19]:
yop.head()

0    1
1    1
2    2
3    2
4    1
Name: Output_Class, dtype: int64

In [20]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split, learning_curve
X_trainc, X_testc, y_trainc, y_testc = train_test_split(Xop, yop, test_size=0.2, random_state=42)

In [21]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (accuracy_score, mean_squared_error, mean_absolute_error,
                             cohen_kappa_score, precision_score, recall_score,
                             f1_score, confusion_matrix, classification_report)

# ---------------- Gradient Boosting Classifier ----------------
gbc = GradientBoostingClassifier(
    n_estimators=200,      # number of boosting stages
    learning_rate=0.1,     # step size shrinkage
    max_depth=3,           # maximum depth of individual trees
    random_state=42
)

gbc.fit(X_trainc, y_trainc)

# ---------------- Predictions ----------------
y_predc = gbc.predict(X_testc)

# ---------------- Error Metrics ----------------
rmse = np.sqrt(mean_squared_error(y_testc, y_predc))
mae = mean_absolute_error(y_testc, y_predc)
kappa = cohen_kappa_score(y_testc, y_predc)
accuracy = accuracy_score(y_testc, y_predc)

# ---------------- Classification Metrics ----------------
precision = precision_score(y_testc, y_predc, average='weighted')
recall = recall_score(y_testc, y_predc, average='weighted')
f1 = f1_score(y_testc, y_predc, average='weighted')

# ---------------- Print Results ----------------
print("Performance Analysis (Gradient boost Classifier first result)")
print("-" * 60)
print(f"Accuracy: {accuracy:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"Cohen's Kappa: {kappa:.4f}")
print("-" * 60)
print(f"Precision (Weighted): {precision:.4f}")
print(f"Recall (Weighted):    {recall:.4f}")
print(f"F1 Score (Weighted):  {f1:.4f}")
print("-" * 60)
print("Confusion Matrix:")
print(confusion_matrix(y_testc, y_predc))
print("-" * 60)
print("Classification Report:")
print(classification_report(y_testc, y_predc))

Performance Analysis (Gradient boost Classifier first result)
------------------------------------------------------------
Accuracy: 0.5982
RMSE: 0.6944
MAE: 0.4286
Cohen's Kappa: 0.3963
------------------------------------------------------------
Precision (Weighted): 0.5935
Recall (Weighted):    0.5982
F1 Score (Weighted):  0.5951
------------------------------------------------------------
Confusion Matrix:
[[23  9  2]
 [12 20 11]
 [ 1 10 24]]
------------------------------------------------------------
Classification Report:
              precision    recall  f1-score   support

           1       0.64      0.68      0.66        34
           2       0.51      0.47      0.49        43
           3       0.65      0.69      0.67        35

    accuracy                           0.60       112
   macro avg       0.60      0.61      0.60       112
weighted avg       0.59      0.60      0.60       112



In [22]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import (make_scorer)
from scipy.stats import randint, uniform


# ---------------- Define Model ----------------
gbc = GradientBoostingClassifier(random_state=42)

# ---------------- Hyperparameter Distribution ----------------
param_dist = {
    'n_estimators': randint(100, 500),
    'learning_rate': uniform(0.01, 0.3),
    'max_depth': randint(2, 10),
    'min_samples_split': randint(2, 20),
    'min_samples_leaf': randint(1, 10),
    'subsample': uniform(0.6, 0.4),   # fraction of samples for each tree
    'max_features': ['sqrt', 'log2', None]
}

# ---------------- Define Kappa Scorer ----------------
kappa_scorer = make_scorer(cohen_kappa_score)

# ---------------- Randomized Search CV (cv=10) ----------------
random_search = RandomizedSearchCV(
    estimator=gbc,
    param_distributions=param_dist,
    n_iter=50,
    scoring=kappa_scorer,
    cv=10,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

# Fit model
random_search.fit(X_trainc, y_trainc)

# ---------------- Best Model ----------------
best_gbc = random_search.best_estimator_
print("Best Hyperparameters:", random_search.best_params_)

# ---------------- Predictions ----------------
y_predc = best_gbc.predict(X_testc)

# ---------------- Error Metrics ----------------
rmse = np.sqrt(mean_squared_error(y_testc, y_predc))
mae = mean_absolute_error(y_testc, y_predc)
kappa = cohen_kappa_score(y_testc, y_predc)
accuracy = accuracy_score(y_testc, y_predc)

# ---------------- Classification Metrics ----------------
precision = precision_score(y_testc, y_predc, average='weighted')
recall = recall_score(y_testc, y_predc, average='weighted')
f1 = f1_score(y_testc, y_predc, average='weighted')


# ---------------- Print Results ----------------
print("\nPerformance Analysis (Gradient Boosting Classifier with Random Search CV - 10 fold first result)")
print("-" * 75)
print(f"Accuracy: {accuracy:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"Cohen's Kappa: {kappa:.4f}")
print("-" * 75)
print(f"Precision (Weighted): {precision:.4f}")
print(f"Recall (Weighted):    {recall:.4f}")
print(f"F1 Score (Weighted):  {f1:.4f}")
print("-" * 75)
print("Confusion Matrix:")
print(confusion_matrix(y_testc, y_predc))
print("-" * 75)
print("Detailed Classification Report:")
print(classification_report(y_testc, y_predc))


Fitting 10 folds for each of 50 candidates, totalling 500 fits
Best Hyperparameters: {'learning_rate': 0.17838315927084888, 'max_depth': 8, 'max_features': 'log2', 'min_samples_leaf': 7, 'min_samples_split': 10, 'n_estimators': 306, 'subsample': 0.7710164073434198}

Performance Analysis (Gradient Boosting Classifier with Random Search CV - 10 fold first result)
---------------------------------------------------------------------------
Accuracy: 0.5714
RMSE: 0.8183
MAE: 0.5089
Cohen's Kappa: 0.3607
---------------------------------------------------------------------------
Precision (Weighted): 0.5712
Recall (Weighted):    0.5714
F1 Score (Weighted):  0.5651
---------------------------------------------------------------------------
Confusion Matrix:
[[22  6  6]
 [16 18  9]
 [ 3  8 24]]
---------------------------------------------------------------------------
Detailed Classification Report:
              precision    recall  f1-score   support

           1       0.54      0.65      

In [23]:
random_search1 = RandomizedSearchCV(
    estimator=gbc,
    param_distributions=param_dist,
    n_iter=30,
    scoring=kappa_scorer,
    cv=10,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

# Fit model
random_search1.fit(X_trainc, y_trainc)

# ---------------- Best Model ----------------
best_gbc1 = random_search.best_estimator_
print("Best Hyperparameters:", random_search1.best_params_)

# ---------------- Predictions ----------------
y_predc1 = best_gbc1.predict(X_testc)

# ---------------- Error Metrics ----------------
rmse = np.sqrt(mean_squared_error(y_testc, y_predc1))
mae = mean_absolute_error(y_testc, y_predc1)
kappa = cohen_kappa_score(y_testc, y_predc)
accuracy = accuracy_score(y_testc, y_predc1)
# ---------------- Print Results ----------------
print("\nPerformance Analysis (Gradient Boosting Classifier with Random Search CV - 10 fold second result)")
print("-" * 75)
print(f"Accuracy: {accuracy:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"Cohen's Kappa: {kappa:.4f}")


Fitting 10 folds for each of 30 candidates, totalling 300 fits
Best Hyperparameters: {'learning_rate': 0.17838315927084888, 'max_depth': 8, 'max_features': 'log2', 'min_samples_leaf': 7, 'min_samples_split': 10, 'n_estimators': 306, 'subsample': 0.7710164073434198}

Performance Analysis (Gradient Boosting Classifier with Random Search CV - 10 fold second result)
---------------------------------------------------------------------------
Accuracy: 0.5714
RMSE: 0.8183
MAE: 0.5089
Cohen's Kappa: 0.3607


In [25]:
from sklearn.model_selection import train_test_split, GridSearchCV
# ---------------- Define Model ----------------
gbc = GradientBoostingClassifier(random_state=42)

# ---------------- Hyperparameter Grid ----------------
param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.05, 0.1, 0.2],
    'max_depth': [3, 4, 5, 6],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'subsample': [0.7, 0.8, 1.0],
    'max_features': [None, 'sqrt', 'log2']
}

# ---------------- Define Kappa Scorer ----------------
kappa_scorer = make_scorer(cohen_kappa_score)

# ---------------- Grid Search CV (cv=10) ----------------
grid_search = GridSearchCV(
    estimator=gbc,
    param_grid=param_grid,
    scoring=kappa_scorer,
    cv=10,
    verbose=1,
    n_jobs=-1
)

# Fit model
grid_search.fit(X_trainc, y_trainc)

# ---------------- Best Model ----------------
best_gbc = grid_search.best_estimator_
print("Best Hyperparameters:", grid_search.best_params_)

# ---------------- Predictions ----------------
y_predc = best_gbc.predict(X_testc)

# ---------------- Error Metrics ----------------
rmse = np.sqrt(mean_squared_error(y_testc, y_predc))
mae = mean_absolute_error(y_testc, y_predc)
kappa = cohen_kappa_score(y_testc, y_predc)
accuracy = accuracy_score(y_testc, y_predc)


# ---------------- Print Results ----------------
print("\nPerformance Analysis (Gradient Boosting Classifier with Grid Search CV - 10 fold)")
print("-" * 75)
print(f"Accuracy: {accuracy:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")
print(f"Cohen's Kappa: {kappa:.4f}")
print("-" * 75)
print("Confusion Matrix:")
print(confusion_matrix(y_testc, y_predc))
print("-" * 60)
print("Classification Report:")
print(classification_report(y_testc, y_predc))

Fitting 10 folds for each of 2916 candidates, totalling 29160 fits


KeyboardInterrupt: 